// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Theatre struct {
	TheatreID *int      `json:"theatreId"`
	Location  *Location `json:"location"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
