// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewAuthor struct {
	ID        *int    `json:"id"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Email     *string `json:"email"`
}

type NewPost struct {
	AuthorID *int    `json:"authorId"`
	Title    *string `json:"title"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
